### ISSUE TITLE
How to install? two months searching twrp for moto edge 30 DUBAI 

### ISSUE THREAD

**Issue by Z3R0NULL** [moto-SM7325-AE/android_device_motorola_dubai-twrp#1]
Please idk how to use your repo i want to install twrp, you should give me instruccions please <3 thank you grettings from argentina

**Comment by ThEMarD** [comment]
Heyyo, unfortunately, it does not work correctly, it only works with stock ROM and fails to work when there's custom ROM. I have given up working on TWRP as I'd rather focus on LineageOS and I have a bunch of devices to maintain
